name: Arduino Sketches

on:
  push:
  pull_request:

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1.1.2
        with:
          # Full qualified board name, with Boards Manager URL if needed
          fqbn: arduino:avr:nano      
          sketch-paths: |
            - ./
          libraries: |
            - name: Adafruit SSD1306
            - name: Adafruit GFX Library
            - name: Adafruit BusIO
      
    
    

   
