name: Arduino Sketches

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v4
      - name: Compile Arduino Sketches
  # You may pin to the exact commit or the version.
  # uses: arduino/compile-sketches@8ac27e99289705c4abec832089575d687b859227
        uses: arduino/compile-sketches@v1.1.2
        with:
          # Full qualified board name, with Boards Manager URL if needed
          fqbn: arduino:avr:nano          
          sketch-paths: 
            -./
      
    
    

   
