name: Arduino Sketches

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1.1.2
        with:
          # Full qualified board name, with Boards Manager URL if needed
          fqbn: arduino:avr:nano      
          sketch-paths: |
            - ./
      
    
    

   
