name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
    -uses: actions/checkout-v2
    -uses: arduino/compile-sketches@v1.1.2
      with: 
        sketch-paths: 
          - ./
        libraries:
        #none
        -
      
    
    

   
